version: '3.8'
services:
  cocina-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocina-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  cocina-web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: cocina-web
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - app-network
    depends_on:
      - cocina-app

  cocina-db:
    image: mysql:5.7
    container_name: cocina-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cocina
    ports:
      - "33008:3306"
    volumes:
      - cocina-dbdata:/var/lib/mysql
    networks:
      - app-network

  redis-cocina:
    image: redis:alpine
    container_name: redis-cocina
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cocina-dbdata:
    driver: local
