FROM node:18

WORKDIR /app

COPY package*.json ./

# Instalar dependencias de npm y Angular CLI globalmente
RUN npm install
RUN npm install -g @angular/cli

COPY . .

EXPOSE 4200

CMD ["npm", "start"]
